# Default values for rbln-npu-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nfd:
  enabled: true

name: rbln
workloadType: "vm-passthrough"

operator:
  image:
    repository: quay.io/edgestack/rbln-npu-operator
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  service:
    port: 8443
    targetPort: 8443

daemonsets: {}

devicePlugin:
  enabled: true
  image: rebellions/k8s-device-plugin
  imagePullPolicy: IfNotPresent
  version: latest
  resourceList:
  - productCardNames:
    - RBLN-CA12
    - RBLN-CA22
    - RBLN-CA25
    resourceName: ATOM
    resourcePrefix: rebellions.ai

metricsExporter:
  enabled: true
  image: rebellions/rbln-metrics-exporter
  imagePullPolicy: IfNotPresent
  version: latest

npuFeatureDiscovery:
  enabled: true
  image: rebellions/rbln-npu-feature-discovery
  imagePullPolicy: IfNotPresent
  version: latest

sandboxDevicePlugin:
  enabled: true
  image: rebellions/k8s-device-plugin
  imagePullPolicy: IfNotPresent
  priorityClassName: system-node-critical
  version: latest
  vfioChecker:
    image: rebellions/rbln-vfio-manager
    version: "latest"
  resourceList:
  - productCardNames:
    - RBLN-CA12
    resourceName: RBLNCA12_PF
    resourcePrefix: rebellions.ai
  - productCardNames:
    - RBLN-CA25
    resourceName: RBLNCA25_PF
    resourcePrefix: rebellions.ai

vfioManager:
  enabled: true
  image: rebellions/rbln-vfio-manager
  imagePullPolicy: IfNotPresent
  priorityClassName: system-node-critical
  version: "latest"
