---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{ include "rbln-k8s-operator.labels" . | nindent 4 }}
  name: rbln-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rbln-operator
subjects:
  - kind: ServiceAccount
    name: rbln-operator-controller-manager
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbln-operator-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rbln-operator-metrics-auth
subjects:
  - kind: ServiceAccount
    name: rbln-operator-controller-manager
    namespace: {{ .Release.Namespace }}
