---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{ include "rbln-npu-operator.labels" . | nindent 4 }}
  name: rbln-operator
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - nodes
      - pods
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rebellions.ai
    resources:
      - rblnclusterpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rebellions.ai
    resources:
      - rblnclusterpolicies/finalizers
    verbs:
      - update
  - apiGroups:
      - rebellions.ai
    resources:
      - rblnclusterpolicies/status
    verbs:
      - get
      - patch
      - update
