apiVersion: rebellions.ai/v1beta1
kind: RBLNClusterPolicy
metadata:
  labels:
    {{ include "rbln-k8s-operator.labels" . | nindent 4 }}
  name: rbln-cluster-policy
  namespace: {{ .Values.operator.namespace }}
spec:
  {{- if .Values.workloadType }}
  workloadType: {{ .Values.workloadType }}
  {{- end }}
  daemonsets: {{ toYaml .Values.daemonsets | nindent 4 }}
  devicePlugin:
    enabled: {{ .Values.devicePlugin.enabled }}
    image: {{ .Values.devicePlugin.image }}
    imagePullPolicy: {{ .Values.devicePlugin.imagePullPolicy }}
    version: {{ .Values.devicePlugin.version }}
  metricsExporter:
    enabled: {{ .Values.metricsExporter.enabled }}
    image: {{ .Values.metricsExporter.image }}
    imagePullPolicy: {{ .Values.metricsExporter.imagePullPolicy }}
    version: {{ .Values.metricsExporter.version }}
  name: {{ .Values.name }}
  npuFeatureDiscovery:
    enabled: {{ .Values.npuFeatureDiscovery.enabled }}
    image: {{ .Values.npuFeatureDiscovery.image }}
    imagePullPolicy: {{ .Values.npuFeatureDiscovery.imagePullPolicy }}
    version: {{ .Values.npuFeatureDiscovery.version }}
  sandboxDevicePlugin:
    enabled: {{ .Values.sandboxDevicePlugin.enabled }}
    image: {{ .Values.sandboxDevicePlugin.image }}
    imagePullPolicy: {{ .Values.sandboxDevicePlugin.imagePullPolicy }}
    priorityClassName: {{ .Values.sandboxDevicePlugin.priorityClassName }}
    version: {{ .Values.sandboxDevicePlugin.version }}
    vfioChecker:
      image: {{ .Values.sandboxDevicePlugin.vfioChecker.image }}
      version: {{ .Values.sandboxDevicePlugin.vfioChecker.version | quote }}
  vfioManager:
    enabled: {{ .Values.vfioManager.enabled }}
    image: {{ .Values.vfioManager.image }}
    imagePullPolicy: {{ .Values.vfioManager.imagePullPolicy }}
    priorityClassName: {{ .Values.vfioManager.priorityClassName }}
    version: {{ .Values.vfioManager.version | quote }}